/**
 * Seed realistic conversation history for the dashboard demo.
 *
 *   npm run seed:demo          add the demo history
 *   npm run seed:demo -- --reset   clear existing history first
 *
 * Rows are written directly rather than generated by running the real pipeline. That costs
 * nothing, it is repeatable, and — more importantly — it lets the mix be shaped deliberately.
 * A gaps screen only makes its point when the same question appears six times; left to chance,
 * fifty random questions produce fifty rows of one and the screen looks like noise.
 *
 * Two things are modelled on purpose:
 *
 *   Clustering — unanswered questions repeat, because that is what a real gap looks like and
 *   it is what turns the screen into a to-do list rather than a log.
 *
 *   Out-of-hours timing — a third of these land in the evening or at the weekend, when the
 *   practice is shut. That is the pitch made visible: these are the enquiries a clinic
 *   currently loses to an answerphone.
 */

import './load-env';
import { getSupabase } from '../src/lib/supabase';

const DAYS = 14;

/**
 * Questions the documents answer, with how often each was asked.
 *
 * The counts matter as much as the questions. A first pass gave every answered question a
 * single ask and repeated only the gaps, which produced a headline of "39% answered instantly"
 * — a demo that argues against the product. Real support traffic is the opposite shape: a small
 * number of dull questions asked constantly, and a long tail of gaps. Fees and opening hours
 * dominate here for the same reason they dominate a real front desk.
 */
const ANSWERED: Array<[string, number]> = [
  ['How much is a check-up?', 14],
  ['How much is a check up for a new patient?', 6],
  ['What are your opening hours?', 11],
  ['Are you open on Saturdays?', 7],
  ['Are you taking NHS patients?', 9],
  ['Do I pay for my kids dental treatment?', 4],
  ['What happens if I miss my appointment?', 5],
  ['How much notice do I need to give to cancel?', 6],
  ['Is there parking?', 8],
  ['How much is a filling?', 9],
  ['What does a crown cost?', 6],
  ['Do you do teeth whitening?', 5],
  ['Can I pay for a crown in instalments?', 3],
  ['Do you accept Bupa?', 4],
  ['Can I smoke after having a tooth out?', 3],
  ['How long before I can rinse after an extraction?', 2],
  ['My temporary crown came off, what should I do?', 3],
  ['What do I need to bring to my first appointment?', 4],
  ['Do you do implants?', 5],
  ['Can I book a filling online?', 3],
  ['Is the practice wheelchair accessible?', 3],
  ['What time do you close on Friday?', 6],
  ['Do I have to stay with my child during their appointment?', 2],
  ['If I need three fillings do I pay three times?', 3],
  ["I'm nervous about the dentist, can I visit first?", 4],
  ['How much is the hygienist?', 7],
  ['Which buses stop near you?', 2],
  ['Are you open on bank holidays?', 3],
];

/**
 * Questions the documents do not answer. Deliberately repeated — the count is the insight.
 * Each entry is [question, how many times it was asked].
 */
const UNANSWERED: Array<[string, number]> = [
  ['Do you offer sedation for nervous patients?', 6],
  ['Do you do sedation? I am terrified of needles', 2],
  ['How much for a rugby mouthguard?', 4],
  ['How long is the wait to join your NHS list?', 5],
  ['Do you do home visits for my mother, she is housebound?', 3],
  ['Do you offer Botox or lip fillers?', 2],
  ['How long do I wear retainers after aligners?', 2],
  ['Is there a hearing loop at reception?', 1],
  ['Can I bring my assistance dog?', 1],
  ['Do you offer a student discount?', 1],
];

/** Leads left after an unanswered question. Contact details are obviously fictional. */
const LEADS = [
  ['Sarah Whitfield', 's.whitfield@example.com', null, 'Do you offer sedation for nervous patients?'],
  ['James Okonkwo', null, '07700 900412', 'How much for a rugby mouthguard?'],
  ['Priya Raman', 'p.raman@example.com', null, 'How long is the wait to join your NHS list?'],
  ['Tom Beckett', null, '07700 900187', 'Do you do home visits for my mother, she is housebound?'],
  ['Aisha Mahmood', 'aisha.m@example.com', null, 'Do you offer sedation for nervous patients?'],
  ['Danny Fletcher', null, '07700 900733', 'Do you do sedation? I am terrified of needles'],
  ['Ruth Ellery', 'r.ellery@example.com', null, 'How long do I wear retainers after aligners?'],
  ['Marcus Bell', null, '07700 900266', 'Do you offer Botox or lip fillers?'],
  ['Helen Nkemelu', 'h.nkemelu@example.com', null, 'Do you do home visits for my mother, she is housebound?'],
] as const;

/**
 * A timestamp within the last `DAYS`, weighted so a third falls outside opening hours.
 *
 * This is the detail that makes the dashboard argue for itself: a clinic looking at their own
 * gaps report should be able to see that a third of these arrived when nobody was there to
 * pick up the phone.
 */
function timestamp(seed: number): Date {
  const day = seed % DAYS;
  const outOfHours = seed % 3 === 0;

  const hour = outOfHours
    ? [19, 20, 21, 22, 7][seed % 5]
    : [9, 10, 11, 12, 14, 15, 16][seed % 7];

  const date = new Date();
  date.setDate(date.getDate() - day);
  date.setHours(hour, (seed * 17) % 60, (seed * 7) % 60, 0);

  // Setting the hour after subtracting days can land in the future — day 0 at 21:00 when it is
  // currently mid-afternoon. That surfaced in the dashboard as "asked -1 days ago". Push any
  // such row back a day rather than clamping to now, which would pile rows onto this minute.
  if (date.getTime() > Date.now()) date.setDate(date.getDate() - 1);

  return date;
}

async function main() {
  const supabase = getSupabase();
  const reset = process.argv.includes('--reset');

  if (reset) {
    // Leads are deleted explicitly. Messages cascade from conversations, but leads are
    // deliberately `on delete set null` in the schema — a patient's contact details should
    // outlive their transcript being purged, because the details are the valuable part. Right
    // for the product, and the reason a reset has to name them separately.
    const { error: leadError } = await supabase.from('leads').delete().not('id', 'is', null);
    if (leadError) throw new Error(`Could not clear leads: ${leadError.message}`);

    const { error } = await supabase.from('conversations').delete().neq('session_id', '');
    if (error) throw new Error(`Could not clear history: ${error.message}`);

    console.log('Cleared existing conversations and leads.\n');
  }

  const turns: Array<{ question: string; answered: boolean }> = [];

  for (const [question, count] of ANSWERED) {
    for (let n = 0; n < count; n++) turns.push({ question, answered: true });
  }
  for (const [question, count] of UNANSWERED) {
    for (let n = 0; n < count; n++) turns.push({ question, answered: false });
  }

  console.log(`Seeding ${turns.length} conversations across ${DAYS} days...`);

  const pendingLeads = [...LEADS];

  let created = 0;

  for (const [index, turn] of turns.entries()) {
    const at = timestamp(index);

    const { data: conversation, error: convError } = await supabase
      .from('conversations')
      .insert({
        session_id: `demo-${index}-${at.getTime()}`,
        started_at: at.toISOString(),
        last_active_at: at.toISOString(),
      })
      .select('id')
      .single();

    if (convError) throw new Error(`Conversation insert failed: ${convError.message}`);

    await supabase.from('messages').insert([
      {
        conversation_id: conversation.id,
        role: 'user',
        content: turn.question,
        was_answered: null,
        created_at: at.toISOString(),
      },
      {
        conversation_id: conversation.id,
        role: 'assistant',
        content: turn.answered
          ? 'Answered from the practice information.'
          : "We don't have that in our practice information — I can pass your question on.",
        was_answered: turn.answered,
        created_at: new Date(at.getTime() + 4000).toISOString(),
      },
    ]);

    // Attach a lead to the first matching unanswered conversation.
    if (!turn.answered) {
      const match = pendingLeads.findIndex((l) => l[3] === turn.question);
      if (match !== -1) {
        const [name, email, phone, reason] = pendingLeads.splice(match, 1)[0];
        await supabase.from('leads').insert({
          conversation_id: conversation.id,
          name,
          email,
          phone,
          reason,
          created_at: new Date(at.getTime() + 40000).toISOString(),
        });
      }
    }

    created++;
  }

  const { count: unanswered } = await supabase
    .from('messages')
    .select('*', { count: 'exact', head: true })
    .eq('was_answered', false);

  const { count: leadCount } = await supabase
    .from('leads')
    .select('*', { count: 'exact', head: true });

  console.log(`\n${created} conversations, ${unanswered} unanswered questions, ${leadCount} leads.`);
  console.log('Dashboard has something worth looking at now.');
}

main().catch((cause) => {
  console.error(`\n${cause instanceof Error ? cause.message : String(cause)}`);
  process.exit(1);
});
